# Generated by Django 6.0.3 on 2026-04-06 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("BirdSound", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bird",
            old_name="height",
            new_name="length",
        ),
    ]
