# Generated by Django 6.0.3 on 2026-04-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BirdSound', '0005_alter_bird_conservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
